/**
 * Mindwm API
 * This document describes the documentation, a collection of JSON schemas and example cloudevent and payloads
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Neo4jChangeDataCaptureRelationshipPayloadEnd from './Neo4jChangeDataCaptureRelationshipPayloadEnd';

/**
 * The Neo4jChangeDataCaptureRelationshipPayload model module.
 * @module model/Neo4jChangeDataCaptureRelationshipPayload
 * @version 0.1.0
 */
class Neo4jChangeDataCaptureRelationshipPayload {
    /**
     * Constructs a new <code>Neo4jChangeDataCaptureRelationshipPayload</code>.
     * @alias module:model/Neo4jChangeDataCaptureRelationshipPayload
     * @param after {Object} 
     * @param before {String} 
     * @param end {module:model/Neo4jChangeDataCaptureRelationshipPayloadEnd} 
     * @param id {String} 
     * @param label {String} 
     * @param start {module:model/Neo4jChangeDataCaptureRelationshipPayloadEnd} 
     * @param type {String} 
     */
    constructor(after, before, end, id, label, start, type) { 
        
        Neo4jChangeDataCaptureRelationshipPayload.initialize(this, after, before, end, id, label, start, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, after, before, end, id, label, start, type) { 
        obj['after'] = after;
        obj['before'] = before;
        obj['end'] = end;
        obj['id'] = id;
        obj['label'] = label;
        obj['start'] = start;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>Neo4jChangeDataCaptureRelationshipPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Neo4jChangeDataCaptureRelationshipPayload} obj Optional instance to populate.
     * @return {module:model/Neo4jChangeDataCaptureRelationshipPayload} The populated <code>Neo4jChangeDataCaptureRelationshipPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Neo4jChangeDataCaptureRelationshipPayload();

            if (data.hasOwnProperty('after')) {
                obj['after'] = ApiClient.convertToType(data['after'], Object);
            }
            if (data.hasOwnProperty('before')) {
                obj['before'] = ApiClient.convertToType(data['before'], 'String');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = Neo4jChangeDataCaptureRelationshipPayloadEnd.constructFromObject(data['end']);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = Neo4jChangeDataCaptureRelationshipPayloadEnd.constructFromObject(data['start']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Neo4jChangeDataCaptureRelationshipPayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Neo4jChangeDataCaptureRelationshipPayload</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Neo4jChangeDataCaptureRelationshipPayload.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['before'] && !(typeof data['before'] === 'string' || data['before'] instanceof String)) {
            throw new Error("Expected the field `before` to be a primitive type in the JSON string but got " + data['before']);
        }
        // validate the optional field `end`
        if (data['end']) { // data not null
          Neo4jChangeDataCaptureRelationshipPayloadEnd.validateJSON(data['end']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['label'] && !(typeof data['label'] === 'string' || data['label'] instanceof String)) {
            throw new Error("Expected the field `label` to be a primitive type in the JSON string but got " + data['label']);
        }
        // validate the optional field `start`
        if (data['start']) { // data not null
          Neo4jChangeDataCaptureRelationshipPayloadEnd.validateJSON(data['start']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}

Neo4jChangeDataCaptureRelationshipPayload.RequiredProperties = ["after", "before", "end", "id", "label", "start", "type"];

/**
 * @member {Object} after
 */
Neo4jChangeDataCaptureRelationshipPayload.prototype['after'] = undefined;

/**
 * @member {String} before
 */
Neo4jChangeDataCaptureRelationshipPayload.prototype['before'] = undefined;

/**
 * @member {module:model/Neo4jChangeDataCaptureRelationshipPayloadEnd} end
 */
Neo4jChangeDataCaptureRelationshipPayload.prototype['end'] = undefined;

/**
 * @member {String} id
 */
Neo4jChangeDataCaptureRelationshipPayload.prototype['id'] = undefined;

/**
 * @member {String} label
 */
Neo4jChangeDataCaptureRelationshipPayload.prototype['label'] = undefined;

/**
 * @member {module:model/Neo4jChangeDataCaptureRelationshipPayloadEnd} start
 */
Neo4jChangeDataCaptureRelationshipPayload.prototype['start'] = undefined;

/**
 * @member {String} type
 */
Neo4jChangeDataCaptureRelationshipPayload.prototype['type'] = undefined;






export default Neo4jChangeDataCaptureRelationshipPayload;

