/**
 * Mindwm API
 * This document describes the documentation, a collection of JSON schemas and example cloudevent and payloads
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Neo4jChangeDataCaptureMeta from './Neo4jChangeDataCaptureMeta';
import Neo4jChangeDataCapturePayload from './Neo4jChangeDataCapturePayload';
import Neo4jChangeDataCaptureSchema from './Neo4jChangeDataCaptureSchema';

/**
 * The Neo4jChangeDataCapture model module.
 * @module model/Neo4jChangeDataCapture
 * @version 0.1.0
 */
class Neo4jChangeDataCapture {
    /**
     * Constructs a new <code>Neo4jChangeDataCapture</code>.
     * @alias module:model/Neo4jChangeDataCapture
     * @param headers {Object.<String, Object>} 
     * @param messageKey {String} 
     * @param meta {module:model/Neo4jChangeDataCaptureMeta} 
     * @param offset {Number} 
     * @param partition {Number} 
     * @param sourceType {String} 
     * @param timestamp {Date} 
     * @param topic {String} 
     * @param schema {module:model/Neo4jChangeDataCaptureSchema} 
     * @param payload {module:model/Neo4jChangeDataCapturePayload} 
     */
    constructor(headers, messageKey, meta, offset, partition, sourceType, timestamp, topic, schema, payload) { 
        
        Neo4jChangeDataCapture.initialize(this, headers, messageKey, meta, offset, partition, sourceType, timestamp, topic, schema, payload);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, headers, messageKey, meta, offset, partition, sourceType, timestamp, topic, schema, payload) { 
        obj['headers'] = headers;
        obj['message_key'] = messageKey;
        obj['meta'] = meta;
        obj['offset'] = offset;
        obj['partition'] = partition;
        obj['source_type'] = sourceType;
        obj['timestamp'] = timestamp;
        obj['topic'] = topic;
        obj['schema'] = schema;
        obj['payload'] = payload;
    }

    /**
     * Constructs a <code>Neo4jChangeDataCapture</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Neo4jChangeDataCapture} obj Optional instance to populate.
     * @return {module:model/Neo4jChangeDataCapture} The populated <code>Neo4jChangeDataCapture</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Neo4jChangeDataCapture();

            if (data.hasOwnProperty('headers')) {
                obj['headers'] = ApiClient.convertToType(data['headers'], {'String': Object});
            }
            if (data.hasOwnProperty('message_key')) {
                obj['message_key'] = ApiClient.convertToType(data['message_key'], 'String');
            }
            if (data.hasOwnProperty('meta')) {
                obj['meta'] = Neo4jChangeDataCaptureMeta.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('partition')) {
                obj['partition'] = ApiClient.convertToType(data['partition'], 'Number');
            }
            if (data.hasOwnProperty('source_type')) {
                obj['source_type'] = ApiClient.convertToType(data['source_type'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('topic')) {
                obj['topic'] = ApiClient.convertToType(data['topic'], 'String');
            }
            if (data.hasOwnProperty('schema')) {
                obj['schema'] = Neo4jChangeDataCaptureSchema.constructFromObject(data['schema']);
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = Neo4jChangeDataCapturePayload.constructFromObject(data['payload']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Neo4jChangeDataCapture</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Neo4jChangeDataCapture</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Neo4jChangeDataCapture.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message_key'] && !(typeof data['message_key'] === 'string' || data['message_key'] instanceof String)) {
            throw new Error("Expected the field `message_key` to be a primitive type in the JSON string but got " + data['message_key']);
        }
        // validate the optional field `meta`
        if (data['meta']) { // data not null
          Neo4jChangeDataCaptureMeta.validateJSON(data['meta']);
        }
        // ensure the json data is a string
        if (data['source_type'] && !(typeof data['source_type'] === 'string' || data['source_type'] instanceof String)) {
            throw new Error("Expected the field `source_type` to be a primitive type in the JSON string but got " + data['source_type']);
        }
        // ensure the json data is a string
        if (data['topic'] && !(typeof data['topic'] === 'string' || data['topic'] instanceof String)) {
            throw new Error("Expected the field `topic` to be a primitive type in the JSON string but got " + data['topic']);
        }
        // validate the optional field `schema`
        if (data['schema']) { // data not null
          Neo4jChangeDataCaptureSchema.validateJSON(data['schema']);
        }
        // validate the optional field `payload`
        if (data['payload']) { // data not null
          Neo4jChangeDataCapturePayload.validateJSON(data['payload']);
        }

        return true;
    }


}

Neo4jChangeDataCapture.RequiredProperties = ["headers", "message_key", "meta", "offset", "partition", "source_type", "timestamp", "topic", "schema", "payload"];

/**
 * @member {Object.<String, Object>} headers
 */
Neo4jChangeDataCapture.prototype['headers'] = undefined;

/**
 * @member {String} message_key
 */
Neo4jChangeDataCapture.prototype['message_key'] = undefined;

/**
 * @member {module:model/Neo4jChangeDataCaptureMeta} meta
 */
Neo4jChangeDataCapture.prototype['meta'] = undefined;

/**
 * @member {Number} offset
 */
Neo4jChangeDataCapture.prototype['offset'] = undefined;

/**
 * @member {Number} partition
 */
Neo4jChangeDataCapture.prototype['partition'] = undefined;

/**
 * @member {String} source_type
 */
Neo4jChangeDataCapture.prototype['source_type'] = undefined;

/**
 * @member {Date} timestamp
 */
Neo4jChangeDataCapture.prototype['timestamp'] = undefined;

/**
 * @member {String} topic
 */
Neo4jChangeDataCapture.prototype['topic'] = undefined;

/**
 * @member {module:model/Neo4jChangeDataCaptureSchema} schema
 */
Neo4jChangeDataCapture.prototype['schema'] = undefined;

/**
 * @member {module:model/Neo4jChangeDataCapturePayload} payload
 */
Neo4jChangeDataCapture.prototype['payload'] = undefined;






export default Neo4jChangeDataCapture;

