/**
 * Mindwm API
 * This document describes the documentation, a collection of JSON schemas and example cloudevent and payloads
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Neo4jChangeDataCaptureNodePayload from './Neo4jChangeDataCaptureNodePayload';
import Neo4jChangeDataCaptureRelationshipPayload from './Neo4jChangeDataCaptureRelationshipPayload';
import Neo4jChangeDataCaptureRelationshipPayloadEnd from './Neo4jChangeDataCaptureRelationshipPayloadEnd';

/**
 * The Neo4jChangeDataCapturePayload model module.
 * @module model/Neo4jChangeDataCapturePayload
 * @version 0.1.0
 */
class Neo4jChangeDataCapturePayload {
    /**
     * Constructs a new <code>Neo4jChangeDataCapturePayload</code>.
     * @alias module:model/Neo4jChangeDataCapturePayload
     * @param {(module:model/Neo4jChangeDataCaptureNodePayload|module:model/Neo4jChangeDataCaptureRelationshipPayload)} instance The actual instance to initialize Neo4jChangeDataCapturePayload.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "Neo4jChangeDataCaptureNodePayload") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                Neo4jChangeDataCaptureNodePayload.validateJSON(instance); // throw an exception if no match
                // create Neo4jChangeDataCaptureNodePayload from JS object
                this.actualInstance = Neo4jChangeDataCaptureNodePayload.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into Neo4jChangeDataCaptureNodePayload
            errorMessages.push("Failed to construct Neo4jChangeDataCaptureNodePayload: " + err)
        }

        try {
            if (typeof instance === "Neo4jChangeDataCaptureRelationshipPayload") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                Neo4jChangeDataCaptureRelationshipPayload.validateJSON(instance); // throw an exception if no match
                // create Neo4jChangeDataCaptureRelationshipPayload from JS object
                this.actualInstance = Neo4jChangeDataCaptureRelationshipPayload.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into Neo4jChangeDataCaptureRelationshipPayload
            errorMessages.push("Failed to construct Neo4jChangeDataCaptureRelationshipPayload: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `Neo4jChangeDataCapturePayload` with oneOf schemas Neo4jChangeDataCaptureNodePayload, Neo4jChangeDataCaptureRelationshipPayload. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `Neo4jChangeDataCapturePayload` with oneOf schemas Neo4jChangeDataCaptureNodePayload, Neo4jChangeDataCaptureRelationshipPayload. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>Neo4jChangeDataCapturePayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Neo4jChangeDataCapturePayload} obj Optional instance to populate.
     * @return {module:model/Neo4jChangeDataCapturePayload} The populated <code>Neo4jChangeDataCapturePayload</code> instance.
     */
    static constructFromObject(data, obj) {
        return new Neo4jChangeDataCapturePayload(data);
    }

    /**
     * Gets the actual instance, which can be <code>Neo4jChangeDataCaptureNodePayload</code>, <code>Neo4jChangeDataCaptureRelationshipPayload</code>.
     * @return {(module:model/Neo4jChangeDataCaptureNodePayload|module:model/Neo4jChangeDataCaptureRelationshipPayload)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>Neo4jChangeDataCaptureNodePayload</code>, <code>Neo4jChangeDataCaptureRelationshipPayload</code>.
     * @param {(module:model/Neo4jChangeDataCaptureNodePayload|module:model/Neo4jChangeDataCaptureRelationshipPayload)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = Neo4jChangeDataCapturePayload.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of Neo4jChangeDataCapturePayload from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/Neo4jChangeDataCapturePayload} An instance of Neo4jChangeDataCapturePayload.
     */
    static fromJSON = function(json_string){
        return Neo4jChangeDataCapturePayload.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {Object} after
 */
Neo4jChangeDataCapturePayload.prototype['after'] = undefined;

/**
 * @member {String} before
 */
Neo4jChangeDataCapturePayload.prototype['before'] = undefined;

/**
 * @member {String} id
 */
Neo4jChangeDataCapturePayload.prototype['id'] = undefined;

/**
 * @member {String} type
 */
Neo4jChangeDataCapturePayload.prototype['type'] = undefined;

/**
 * @member {module:model/Neo4jChangeDataCaptureRelationshipPayloadEnd} end
 */
Neo4jChangeDataCapturePayload.prototype['end'] = undefined;

/**
 * @member {String} label
 */
Neo4jChangeDataCapturePayload.prototype['label'] = undefined;

/**
 * @member {module:model/Neo4jChangeDataCaptureRelationshipPayloadEnd} start
 */
Neo4jChangeDataCapturePayload.prototype['start'] = undefined;


Neo4jChangeDataCapturePayload.OneOf = ["Neo4jChangeDataCaptureNodePayload", "Neo4jChangeDataCaptureRelationshipPayload"];

export default Neo4jChangeDataCapturePayload;

