/**
 * Mindwm API
 * This document describes the documentation, a collection of JSON schemas and example cloudevent and payloads
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Neo4jChangeDataCaptureMetaSource model module.
 * @module model/Neo4jChangeDataCaptureMetaSource
 * @version 0.1.0
 */
class Neo4jChangeDataCaptureMetaSource {
    /**
     * Constructs a new <code>Neo4jChangeDataCaptureMetaSource</code>.
     * @alias module:model/Neo4jChangeDataCaptureMetaSource
     * @param hostname {String} 
     */
    constructor(hostname) { 
        
        Neo4jChangeDataCaptureMetaSource.initialize(this, hostname);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hostname) { 
        obj['hostname'] = hostname;
    }

    /**
     * Constructs a <code>Neo4jChangeDataCaptureMetaSource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Neo4jChangeDataCaptureMetaSource} obj Optional instance to populate.
     * @return {module:model/Neo4jChangeDataCaptureMetaSource} The populated <code>Neo4jChangeDataCaptureMetaSource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Neo4jChangeDataCaptureMetaSource();

            if (data.hasOwnProperty('hostname')) {
                obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Neo4jChangeDataCaptureMetaSource</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Neo4jChangeDataCaptureMetaSource</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Neo4jChangeDataCaptureMetaSource.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['hostname'] && !(typeof data['hostname'] === 'string' || data['hostname'] instanceof String)) {
            throw new Error("Expected the field `hostname` to be a primitive type in the JSON string but got " + data['hostname']);
        }

        return true;
    }


}

Neo4jChangeDataCaptureMetaSource.RequiredProperties = ["hostname"];

/**
 * @member {String} hostname
 */
Neo4jChangeDataCaptureMetaSource.prototype['hostname'] = undefined;






export default Neo4jChangeDataCaptureMetaSource;

