/**
 * Mindwm API
 * This document describes the documentation, a collection of JSON schemas and example cloudevent and payloads
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Vector2int model module.
 * @module model/Vector2int
 * @version 0.1.0
 */
class Vector2int {
    /**
     * Constructs a new <code>Vector2int</code>.
     * @alias module:model/Vector2int
     * @param x {Number} the X coordinate
     * @param y {Number} the Y coordinate
     */
    constructor(x, y) { 
        
        Vector2int.initialize(this, x, y);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, x, y) { 
        obj['x'] = x;
        obj['y'] = y;
    }

    /**
     * Constructs a <code>Vector2int</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Vector2int} obj Optional instance to populate.
     * @return {module:model/Vector2int} The populated <code>Vector2int</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Vector2int();

            if (data.hasOwnProperty('x')) {
                obj['x'] = ApiClient.convertToType(data['x'], 'Number');
            }
            if (data.hasOwnProperty('y')) {
                obj['y'] = ApiClient.convertToType(data['y'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Vector2int</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Vector2int</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Vector2int.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

Vector2int.RequiredProperties = ["x", "y"];

/**
 * the X coordinate
 * @member {Number} x
 */
Vector2int.prototype['x'] = undefined;

/**
 * the Y coordinate
 * @member {Number} y
 */
Vector2int.prototype['y'] = undefined;






export default Vector2int;

